version: '3.1'

services:
  db:
    container_name: rss-agg-db
    image: postgres:15
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  db:
